get_jobs_task:
  description: >
    Research job opportunities for the job title {title} and location {location}. Do not include job opportunities
    that do not accept applications anymore. 
    Utilize internet search tools and recommendation engines to gather the information. 
    Utilize only www.linkedin.com.
# and posted less than {posted}.
  expected_output: >
    A structured summary of 20 job opportunities in line with the job title. 
    Each entry should include the job title, location, a description of the company, the size of the company 
    (including the number of employees), the responsibilities, the required technical skills, the salary if available, 
    the website where the job was posted, the date when the job was posted, whether the job is remote, on-site or hybrid. 
  agent: job_searcher

customize_cover_letter_task:
  description: >
    Customize the cover letter for each job opportunity.

    Cover letter file: {path_to_cover_letter}
    Job opportunities file: {path_to_job_opportuntities}
  expected_output: >
    A customized cover letter for each job opportunity. 
  agent: cover_letter_customizer

filter_jobs_task:
  description: >
    Filter the job opportunities to make sure that a job application was not previously submitted
    to the company. Also filter the job opportunities based on human input. Ask a human which job 
    opportunities to keep. 
    
    Job opportunities file: {path_to_job_opportuntities}
    Submitted job opportunities file: {path_to_submitted_applications}
  expected_output: >
    The same structure as the job opportunities but keeping only the job titles with the corresponding company name 
    and whether the job opportunities should be kept or discarded. In case of discarded jobs specify also the motivation.
  agent: filter_job_opportunities

